[Template merge - und] Major bug fix to the generate lemma test script. Now it actually checks that the generated lemmas correspond to the listed ones. Several of the languages had local modifications. Those are brought forward to the new version, to my best effort.

diff --git a/test/src/morphology/generate-noun-lemmas.sh.in b/test/src/morphology/generate-noun-lemmas.sh.in
--- a/test/src/morphology/generate-noun-lemmas.sh.in
+++ b/test/src/morphology/generate-noun-lemmas.sh.in
@@ -17,6 +17,7 @@ lemmas=./nouns.txt
 generatedlemmas=./gen-nouns
 failedlemmas=./fail-lemmas
 generatorfile=./../../../src/generator-gt-norm
+resultfile=lemma-gen-diff
 
 # FAIL if source file does not exist:
 if [ ! -f $sourcefile ]; then
@@ -63,14 +64,30 @@ for f in $fsttype; do
 	fi
 	if [ -f "$generatorfile.$f" ]; then
 		let "transducer_found += 1"
-		sed 's/$/+N+AN+Sg/' $lemmas | \
-				$lookuptool $generatorfile.$f > $generatedlemmas.$f.txt
-		fgrep '?' $generatedlemmas.$f.txt > $failedlemmas.$f.txt
-		if [ $(wc -l $failedlemmas.$f.txt | tr -s ' ' | sed 's/^ //' \
-				| cut -d' ' -f1) -gt 0 ]; then
+
+###### Test non-comopunds: #######
+		# generate animate nouns:
+		sed 's/$/+N+AN+Sg/' $lemmas | $lookuptool $generatorfile.$f \
+			| cut -f2 | fgrep -v "+N+Sg" | grep -v "^$" | sort -u \
+			> $generatedlemmas.$f.txt 
+		# generate inanimate nouns:
+		sed 's/$/+N+AN+Sg/' $lemmas | $lookuptool $generatorfile.$f \
+			| cut -f2 | grep "N+" | cut -d "+" -f1 | sed 's/$/+N+IN+Sg/' \
+			| $lookuptool $generatorfile.$f | cut -f2 \
+			| grep -v "^$" >> $generatedlemmas.$f.txt 
+
+###### Collect results: #######
+		# Sort and compare original input with resulting output - the diff is
+		# stored and opened in SEE:
+		sort -u -o $generatedlemmas.$f.txt $generatedlemmas.$f.txt 
+		comm -23 $lemmas $generatedlemmas.$f.txt > $resultfile.$f.txt
+
+		# if at least one word is found, the test failed, and the list of failed
+		# lemmas is opened in SubEthaEdit:
+		if [ -s $resultfile.$f.txt ]; then
 			# Only open the failed lemmas in see if @SEE@ is defined:
 			if [ "$EXTEDITOR" ]; then
-				$EXTEDITOR $failedlemmas.$f.txt
+				$EXTEDITOR $resultfile.$f.txt
 			fi
 		    Fail=1
 		    echo "$f - FAIL"
@@ -90,5 +107,5 @@ fi
 
 if [ $transducer_found -eq 0 ]; then
     echo ERROR: No transducer found
-    exit 1
+    exit 77
 fi
