[Template merge] fix generate lemma test lexc checks

diff --git a/src/fst/morphology/test/generate-noun-lemmas.sh.in b/src/fst/morphology/test/generate-noun-lemmas.sh.in
--- a/src/fst/morphology/test/generate-noun-lemmas.sh.in
+++ b/src/fst/morphology/test/generate-noun-lemmas.sh.in
@@ -53,6 +53,11 @@ if [ ! `ls -1 $source_file 2>/dev/null | wc -l ` -gt 0 ]; then
     echo
     exit 77
 fi
+if ! test -f "$source_file" ; then
+    printf "%sfail%s missing lexc file %s\n" "$red" "$reset" \
+        "$source_file"
+    exit 1
+fi
 
 # Use autotools mechanisms to only run the configured fst types in the tests:
 fsttype=
